application:
  title: Payment Microservice

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs

spring:
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/caz-payments
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
  profiles:
    active: dev

services:
  connection-timeout-seconds: 29
  read-timeout-seconds: 29
  gov-uk-pay:
    rootUrl: https://publicapi.payments.service.gov.uk
    api-key: to-be-replaced-by-external-value
  sqs:
    new-queue-name: notify-gateway_new_dev.fifo
    template-id: a4282196-a623-4b78-acfa-70b0a0b4a19b

management:
  endpoints:
    web:
      base-path:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

swagger:
  model:
    descriptions:
      payment-status:
        payment-status: Status of the payment. Can be either 'paid', 'refunded' or 'chargeback'
        payment-provider-id: GOV.UK Pay unique payment identifier
        case-reference: >-
          A unique identifier that provides traceability between the central CAZ Service and Local Authority case management
          systems in the event that a payment is subject to some form of customer support query (e.g. a refund or chargeback)
        vrn: Vehicle registration number
        date-of-caz-entry: ISO 8601 formatted date string indicating the date that the vehicle identified by the VRN attribute entered the CAZ.
      payment-info:
        results: An array containig details about payments of queried VRNs
        vrn: Vehicle registration number
        payments: An array containing information about particular payments of the given VRN
        payment-provider-id: GOV.UK Pay unique payment identifier
        total-paid: >-
          The total GBP value of the payment linked to the paymentProviderId.
          If the motorist paid in advance to travel in to the CAZ on multiple dates, then the payment amount will be a multiple
          of the daily charge due (e.g. if the daily charge for a car entering a CAZ is £8.00, but the motorist paid in advance
          for 3 days of travel, then the chargePaid would be equal to £24.00).
          Expressed in pounds and pence format to 2 decimal places.
        payment-date: ISO 8601 formatted date string that specifies the date on which the payment was made via GOV.UK Pay
        payment-status: Status of the payment. Can be either 'paid', 'refunded' or 'chargeback'
        line-items: >-
          Array containing objects that specify the: (1) date(s) for which the vehicle has paid to journey in to the CAZ
          (identified by the x-api-key header parameter); (2) the charge associated with the journey; (3) the payment status of
          the charge (i.e. whether it has been paid or refunded); and, (4) any Local Authority case reference associated with the
          charge (e.g. that may be linked to a customer query relating to the charge).
          1 object will be returned for each date of travel associated with the payment.
        case-reference: >-
          A unique identifier that provides traceability between the central CAZ Service and Local Authority case management systems
          in the event that a payment is subject to some form of customer support query (e.g. a refund or chargeback)
        charge-paid: >-
          The GBP value of the payment linked to the paymentProviderId. If the motorist paid in advance to travel in to the CAZ on multiple
          dates, then the payment amount will be a multiple of the daily charge due (e.g. if the daily charge for a car entering a CAZ
          is £8.00, but the motorist paid in advance for 3 days of travel, then the chargePaid would be equal to £24.00).
          Expressed in pounds and pence format to 2 decimal places
        travel-date: >-
          ISO 8601 formatted date string that specifies a date(s) for which the vehicle has paid to travel in to the CAZ
          (identified by the x-api-key header parameter)
      payment-info-request:
        payment-provider-id: >-
          GOV.UK Pay unique payment identifier. Can be used to obtain data associated with a specific GOV.UK Pay payment transaction.
          Can be specified as an alternative to vrn, fromDatePaidFor and toDatePaidFor to obtain information about a specific payment
          that a vehicle has made to travel in to a CAZ (identified by the x-api-key header parameter).
        vrn: >-
          Identifies a vehicle for the purpose of obtaining information about associated payments that have been made to travel in to
          a CAZ (identified by the x-api-key header parameter). Attribute must exclude whitespace and is case insensitive.
          Typical usage of this attribute would be to specify it in combination with fromDatePaidFor and toDatePaidFor to obtain
          information about the payments associated with a specific vehicle that has paid to travel in to a CAZ
          (identified by the x-api-key header parameter) within a specific date range. If no fromDatePaidFor or toDatePaidFor is
          specified, information about all payments associated with the specified VRN and CAZ (identified by the x-api-key header
          parameter) will be returned.
        from-date-paid-for: >-
          ISO 8601 formatted date string that can be used to obtain information about payments that have been made to travel in to a CAZ
          (identified by the x-api-key header parameter) on the specified date. This date is inclusive. If no VRN is specified, payment
          information for all vehicles that have paid to travel in to a CAZ (identified by the x-api-key header parameter) on the specified
          date will be returned. If no toDatePaidFor is specified, all settled charges for the 24 hour period corresponding to the specified
          date will be returned.
        to-date-paid-for: >-
          ISO 8601 formatted date string that can be used to determine what vehicles have paid to travel in to a CAZ
          (identified by the x-api-key header parameter) during a specified date range. This date is inclusive. If no VRN is specified, all
          settled charges for all vehicles that have paid a charge to enter the CAZ (identified by the x-api-key header parameter) during the
          specified date range will be returned. If no fromDatePaidFor is specified, all settled charges for the prior 24 hour period corresponding
          to the specified date will be returned.
      payment-status-update:
        vrn: Vehicle registration number
        status-updates: An array containing details of separate payment which needs to be updated
        date-caz-entry: ISO 8601 formatted date string. Used in combination with the vrn attribute to uniquely identify a payment whose status requires updating
        payment-status: Status of the payment. Can be either 'paid', 'refunded' or 'chargeback'
        case-reference: >-
          A unique identifier that provides traceability between the central CAZ Service and Local Authority case management systems in the event
          that a payment is subject to some form of customer support query (e.g. a refund or chargeback)
        payment-provider-id: GOV.UK Pay unique payment identifier returned by the payment-status GET method
      vehicle-entrant:
        vrn: Vehicle registration number
        caz-entry-timestamp: ISO 8601 formatted datetime string that specifies the date and time on which the vehicle entered the CAZ
        clean-zone-id: Clean Air Zone identifier
      vehicle-entrant-response:
        status: Payment Status of created Vehicle Entrant
      payments-initiate:
        vrn: Vehicle registration number
        days: Array of ISO 8601 formatted dates string that specifies the dates for which user wants to pay.
        clean-zone-id: Clean Air Zone identifier
        amount: Amount to pay
        return-url: Front end URL used as return URL after payment.


  operations:
    payments:
      create-vehicle-entrant:
        description: >-
          Creates (unless it exists) an entry in the database that represents an entrant of a vehicle into a CAZ.
          Upon completion of this operation the status of the payment associated with the entry is returned
    charge-settlement:
      payment-status-update:
        description: >-
          Allows Local Authorities to update the status of one or more paid CAZ charges to reflect any action that is
          being taken with the payment (e.g. such as the processing of a refund or chargeback)
      payment-status:
        description: >-
          Allows LAs to query and retrieve data that enables them to determine whether a vehicle that has entered their CAZ (a 'vehicle entrant')
          has paid the charge that they are liable for in order to determine whether enforcement action is required
      payment-info:
        description: >-
          Allows LAs to query and retrieve data about a payment that has been made via GOV.UK Pay in relation
          to a vehicle that has entered their CAZ (a 'vehicle entrant')
    db:
      migration:
        description: Evolve DB schema          