version: '3.3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres.docker
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: name_of_your_database
