version: '3.3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres.docker.integration
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caz-payments
