package uk.gov.caz.psr.model;

import java.time.LocalDate;
import java.util.UUID;
import lombok.Builder;
import lombok.NonNull;
import lombok.Value;

/**
 * An entity which represents a row stored in the database in {@code VEHICLE_ENTRANT_PAYMENT}
 * table.
 */
@Value
@Builder(toBuilder = true)
public class VehicleEntrantPayment {

  /**
   * The internal unique identifier auto-generated by the database.
   */
  UUID id;

  /**
   * A unique identifier of {@link VehicleEntrance} entity.
   */
  UUID vehicleEntrantId;

  /**
   * A unique identifier of {@link Payment} entity.
   */
  UUID paymentId;

  /**
   * Vehicle registration number.
   */
  @NonNull
  String vrn;

  /**
   * An identifier of the Clean Air Zone.
   */
  @NonNull
  UUID cleanZoneId;

  /**
   * A date for which the payment is being made.
   */
  @NonNull
  LocalDate travelDate;

  /**
   * The amount of money paid for the vehicle entrant on a given date to the given CAZ.
   */
  @NonNull
  Integer chargePaid;

  /**
   * Status of the payment.
   */
  @NonNull
  PaymentStatus status;

  /**
   * A unique identifier that provides traceability between the central CAZ Service and Local
   * Authority case management systems in the event that a payment is subject to some form of
   * customer support query (e.g. a refund or chargeback).
   */
  String caseReference;
}
