### Integration tests configuration

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url:localhost:9999}/caz-payments
#    url: jdbc:postgresql://${postgres.url:localhost:5432}/caz-payments
