### Integration tests configuration

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url:localhost:9999}/caz-payments
#    url: jdbc:postgresql://${postgres.url:localhost:5432}/caz-payments
    hikari:
      maximum-pool-size: 10

services:
  gov-uk-pay:
    root-url: http://localhost:1080
    api-key: P8P5tyxVL7Qb5