version: '2' # only version 2.x is supported by the maven plugin

services:
  postgres-it:
    image: postgres:11-alpine
    ports:
      # if you modify the port, remember to change it in application's configuration as well
      - 9999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_compliance

  localstack-it:
    image: localstack/localstack:0.11.4
    ports:
      - "4576:4576"
      - "4584:4584"
    environment:
      - SERVICES=sqs,secretsmanager
    volumes:
      - "~/tmp/localstack:/tmp/localstack"
    networks:
      - localstack_network
      
  redis-it:
    image: redis
    container_name: redis.docker
    ports:
      - 6380:6379
      
networks:
  localstack_network:
